set autoindent
set backspace=indent,eol,start
set hlsearch
set ignorecase
set incsearch
set linebreak
set number
set ruler
set shiftwidth=4
set showbreak=+++
set showmatch
set smartcase
set smartindent
set softtabstop=4
set textwidth=100
set undolevels=1000
set visualbell
syntax enable
